== Appendix II

=== Consider Transitioning away from {MSTS} to Open Rails

By 2026, {MSTS} is roughly 25 years old and has long since been abandoned by its creators. The fact that it has lived on this long is a testament to its community, not to the completeness of the original program. Many years after {MSTS} was introduced, and after its planned sequel was cancelled, a team of talented programmers began building an open-source replacement. This is how we got Open Rails.

At some point, most {MSTS} users will want to transition from {MSTS} to {OR}. By design, {OR} has an important advantage: it can use a vast amount of legacy {MSTS} content created over the years. Most content will work without major issues, although some items may need small adjustments to run correctly in {OR}.


=== The {OR} Program

The {OR} program installs in a location that will remain totally isolated from simulator content, which is a fundamental difference from the way {MSTS} works.  The benefits of this approach are numerous but the primary benefit is that you will never need to reinstall content when you perform an update or re-installation of {OR}.  You can completely delete and reinstall {OR} and then inform it about where your content is and you are ready to go.

You can also isolate content, which helps when one content installation affects another. Since content locations can be switched within {OR}, you can select isolated route installations as needed. This eliminates the need for legacy solutions like _Train Store_ with {MSTS}.

Technically, you do not need any {MSTS} content to use {OR}. However, if you have an old {MSTS} installation installed or saved, the beauty of the {OR} solution is that only the following folders need to be copied from the old {MSTS} installation:

* GLOBAL folder
* SOUND folder
* ROUTES folder
* TRAINS folder

All other {MSTS} files are not required and are redundant under {OR}.

[NOTE]
As a content developer, you will still need a set of utilities like Aceit, TGATOOLS2 and FFEDIT_SUB to actually access and manipulate content without the {MSTS} *UTILS* folder.

A typical {OR} solution that does not depend on a complete {MSTS} installation could be set up like this:

Installation

|===
| Program location              | Comment

| C:\Program Files (x86)\Open Rails    | Where the PROGRAM gets installed
|===

Content
|===
| Program location              | Comment

| C:\ORTS\TrainSimulations\     | Any TrainSimulations Freeware/Payware content (Global, Routes, Sound, Trains)
| C:\ORTSWORLD\                 | Copied over legacy MSTS installation content folders (Global, Routes, Sound, Trains)
| C:\ORTS\GNRR                    | Any custom or 3rd party installations that don't have MSTS dependencies
| C:\ORTS\_xxx_                   | Where _XXX_ is any other route that will share (Global, Routes, Sound,Trains) from the OR folder
| C:\ORTS\developer               | Any *work in progress routes*
| C:\ORTS\                        | (Global, Routes, Sound,Trains)
|===





