
== Creating Rolling Stock and Locomotives

In order to ensure the precise functioning of locomotives and other rolling stock, it is crucial to acquire as much authentic data as possible and comprehend the expected behavior of the locomotive or rolling stock.  These bits of collected data will be used to flesh out the `ENG` and `WAG` files that accompany the 3D Model and textures that make up a particular content item that can be added to {OR}.

You would need to gather enough prototypical data to accurately complete the physics descriptions in the `WAG` or `ENG` file. 

[WARNING]
Please note that there have been many improvements and additions to the simulator that go well beyond the capabilities and options of the original {MSTS}.  Many of the options listed in this section contain values and parameters that are unique to {or}. It is assumed that the reader is NOT trying to retain compatibility with legacy {MSTS} and doing so is beyond the scope of this section.  If you wish to retain {MSTS} compatibility, please refer to the technical documents that come with {MSTS}.

[NOTE]
The process of creating content and config files is often described as a complicated mess, and that description is not entirely inaccurate. However, there is a side project underway to develop a set of replacement files for MSTS 3D models, config files, and textures that are free to use and do not violate anyone's copyrights. These replacement files will serve as examples of the standards for creating 3D models, textures, and config files for Open Rails, which can be shared with everyone.


== General Configuration File Format

The formatting of the configuration files are based on a standard known as S-Expression.  This method, known as "symbolic expression format" pre-dates a lot of the more modern programming language solutions for managing data, like JSON or XML.  It was originally devised to build tree-structured data notation and was a commonly used with languages like LISP.  Like LISP, it is heavily dependent on parentheses.  You could even say that XML has a somewhat S-Expression like structure if you are familiar with it.

The SIMIS Game Studio which eventually became KUJU, used this format to store the configuration data for the {MSTS}.  Many of the files that form part of the sim are in one of a number of formats bearing the "SIMISA" signature at the top of the file. The SIMIS file format is identified a 16 byte or longer signature and header, with the remainder of the file being an inner format/data.  For example; you might see `SIMISA@@@@@@@@@@JINX0D0t______` at the top of a file.  This header section does not get compressed with the rest of the file, and is only used to identify the file type. The remaining data is compressed using the Zlib's DEFLATE algorithm.



== Open Rails "Units of Measure"

(((ORTS, "Units")))

[NOTE]
Source: http://www.coalstonewcastle.com.au/physics/or-parameter-uom/

*Aim -* this section describes the standard units of measure (UoM) available in Open Rails Train Simulator. These are the UoM used to input values from the ENG or WAG files.

*Note:*

* The UoM values shown in the "Default" column is the UoM value that OR assumes if no UoM value is included in the parameter statement. *(However it is always good practice to include the relevant UoM)*
* The "Alternative UoMs" column shows alternate UoM currently supported by OR.
* The UoM should directly follow the numerical value in the parameter with any spacing, otherwise it will not be correctly interpreted.

[width="100%",cols="20%,20%,20%,20%,20%",options="header",]
|===
|Unit of Measure |Description |Default UoM |Alternative UoMs |Typical Examples
|Mass |Describes the weight of an object |*kg* |*lb*, *t* (metric tonne), *t-uk* +
(imperial ton), *t-us* (us ton) |Mass ( 106t-us )
|Distance |Describes the length or distance between two points or locations. |*m* |*cm*, *mm*, *km*, *ft*, *in* |WheelRadius ( 21.5in )
|Area |Describes the area of an object. |*m^2* |*ft^2* |ORTSSuperheatArea ( 295ft^2 )
|Volume (of a space) |Describes the volume of an object. |*m^3* |*ft^3*, *in^3* |BoilerVolume ( 340ft^3 )
|Volume (fluid quantity) |Describes the fluid quantity contained by an object. |*l* |*g-uk* (gallons - uk), *g-us* (gals - us) |MaxDieselLevel ( 800g-uk )
|Time |Describes the elapsed time between two events. |*s* |*m*, *h* |
|Current |Describes the current flow in a circuit. |*A* | |MaxCurrent ( 2700A )
|Voltage |Describes the voltage of a circuit. |*V* |*kV* |
|Speed |Describes the speed of an object. |*m/s* |*mph*, *km/h* |Sanding ( 20mph )
|Mass Rate of Change |Describes the rate of change in mass for an object. |*lb/h* |*kg/h* |
|Frequency |Describes the frequency of movement of an object. |*hz* |*rpm*, *rps* |
|Force |Describes the force applied to an object. |*N* |*kN*, *lbf* |MaxForce ( 227kN )
|Power |Describes the power of an object. |*W* |*kW*, *hp* |MaxPower ( 2650hp )
|Pressure |Describes the pressure of an object. |*psi* |*bar*, *kpa*, *inhg* |MaxBoilerPressure ( 250psi )
|Pressure rate of change |Describes the rate of change in pressure of an object. |*psi/s* |*bar/s*, *kpa/s*, *inhg/s* |TrainPipeLeakRate ( 0.01inhg/s )
|Energy Density |Describes the energy density of an object. |*kj/kg* |*btu/lb* |ORTSFuelCalorific ( 13700btu/lb )
|Temperature |Describes the temperature of an object. |*degc* |*degf* |
|Davis B Coefficient |Describes the UoM for the Davis B value. |*ns/m* |*lbf/mph* |
|Davis C Coefficient |Describes the UoM for the Davis C value. |*Nm/s^2* |*lbf/mph^2* |
|Stiffness |Describes the stiffness. |*n/m* | |Stiffness ( 1e6N/m 2e6N/m )
|Rotational Inertia |Describes the inertia due to the rotation of an object. |*kgm^2* | |
|Angle |Describes the angle of an object. |*rad* |deg |ORTSMaximumWheelFlangeAngle ( 75deg )
|===



[NOTE]
The contents of an ENG or WAG file use an S-expression type of notation for grouping of related items. Token definitions are delimited by opening ( and closing ) parenthesis. All strings are quoted using the double quote character (") and are UTF-8 encoded. Tokens can have zero or more attributes. Human readability is a design goal.

[TIP]
With {or} it is very common that things like coupler and brake settings are consistent between many different pieces of rolling stock.  For this reason, it is common to see content releases that share these common settings in a specific folder on the hard drive and make call-outs to the common settings using the {OR} `INCLUDE` token in the `ENG` or `WAG` file.


=== Using _INCLUDE_

(((ORTS, "Using INCLUDE")))

The INCLUDE token is new to {OR} and did not exist in {MSTS}. Using INCLUDE looks like the following example, where this NAVS content `WAG` FILE makes a call-out to FreightAnims for car body and numbers and then coupler and then the remainder of the specific car details: 

[source,]
----
SIMISA@@@@@@@@@@JINX0D0t______

Wagon ( NAVX_105007_MT

	ORTSFreightAnims (
		WagonEmptyWeight ( 64400lb )
		FreightAnimStatic (
			Shape( ../NAVS_COMMON/Flatcar-GS-Type-53-6/Flatcar-GS-Type-53-6_BULK_Carbody-4.s ) <1>
			Offset( 0, 0, 0 )
			FreightWeight( 0lb )
		)
			FreightAnimStatic (
			Shape( ../NAVS_COMMON/Flatcar-GS-Type-53-6/Decals/Flatcar-GS-Type-53-6_Decals_08.s ) <2>
			Offset( 0, 0, 0 )
			FreightWeight( 0lb )
		)
	)

	Include( "../NAVS_COMMON/INCLUDE/AAR_Type-E.inc" ) <3>
	Include( "../NAVS_COMMON/Flatcar-GS-Type-53-6/Flatcar-GS-Type-53-6_S2_Roller_Bulkhead_MT.inc" ) <4>
----
<1> Get the 3D MODEL of this vehicle
<2> Get the additional added modeled items, in this case, the DECALS
<3> Include the common Coupler Type
<4> Include the physics details that define this particular vehicle 


While you *can* continue to place all of your physics data in a single `WAG` or `ENG` file, you might find that this method of including other files helps out when you create many variants of the same basic model. It remains totally optional to make use of this technique.

[NOTE]
The INCLUDE token is a new token that did not exist in {MSTS}. So using it means that you are using a feature that is not supported by the original {MSTS} making the content Open Rails specific.

[TIP]
Erik Cantu has come up with a winning set of options here that would even allow swapping of trucks on an existing model because the trucks are defined in a separate file.


=== Basic ENG and WAG file Details

The goal of this section is to assist the reader when creating new vehicles or when upgrading their old MSTS ENG and WAG files to current ORTS standards.



[WARNING]
The list of Open Rails ENG/WAG file parameters is very likely to be a constantly moving target as new tokens/parameters are being added regularly.

==== Should there be a ENG/WAG standard layout?

So far, we have not been required to follow a rigid standard for ENG and WAG file layout and there is no indication that this will ever change.  While this offers freedom of choice to the developer of content, it has created truly horrific examples of how the s-expression format does not lend itself to good results.  Much uploaded content has suffered from the extra or missing parenthesis due opening and closing pairs not being very visible when spanning many lines of text.  

There *should* also be an attempt by the reader to adopt a standardized or consistent way they create their own ENG/WAG files.  The goal of making these files more easily readable and validated should be attempted.  

One recommendation made by Peter Newell is to separate the contents of these files into sections with comment headers, for example:

----
Comment ( ******************************* General Information *******************************
          Included in this section - Type, Shape, Size, Mass, etc
          *********************************************************************************** )
----

It's not a bad idea, though you actually seldom see it being used.


There are essentially 2 sets of parameter types in {OR}. These are BASIC and ADVANCED settings.  For the most part, BASIC settings are compatible with legacy MSTS while ADVANCED settings are specifically used only in {OR}.

For example:

*Couplers Basic*

* CouplingHasRigidConnection 
* Coupling  - Automatic Bar Chain
* Type 
* Spring 
* Break 
* r0 


*Couplers Advanced*

* ORTSTensionStiffness 
* ORTSTensionR0 
* ORTSTensionSlack 
* ORTSCompressionStiffness 
* ORTSCompressionR0 
* ORTSCompressionSlack 
* ORTSBreak 


==== Universal Settings

(((ORTS, "Universal Settings")))

These settings are found in nearly every type of rolling stock or locomotive content and while some are optional, most are really not.  Many of the new ORTS tokens are related to Derailment Coefficient determination.

|===
| Token									|MSTS	|ORTS	| Parameters

|Type()									| x 	| x		| Steam Diesel Electric Freight Carriage Tender
|Wagon()								| x		| x		| Section contains all related wagon() tokens
|WagonShape() 							| x		| x		| Defines the file path to locate the the shape ".S" file
|Size()									| x     | x		| 3 Dimensions: X Y Z, in meters by default unless a Unit is supplied
|WheelRadius()							| x 	| x		| Wheel Radius in meters unless a Unit is supplied. Example: "33in"	
|ORTSLengthCouplerFace ()				|		| x		| DC - Length between coupler faces (Is this the same a 'length over strikers' + about 24"?)
|ORTSLengthCarBody ()					|		| x		| DC - Actual length of car	
|ORTSLengthBogieCentre ()				|		| x		| DC - Actual length of distance between center of bogies	
|ORTSRigidWheelBase ()					|		| x		| DC - The distance between immovable axles
|ORTSNumberBogies ()					|		| x 	| DC - Number of Bogies on the car
|ORTSNumberAxles ()						|		| x     | DC = Number of total axles for all bogies
|ORTSWheelFlangeLength ()				|		| x 	| DC - Wheel Flange length
|ORTSMaximumWheelFlangeAngle ( 72deg )	|		| x		| DC - (Degrees or Radians) default is radians
|include								|		| x		| Defines the file and path if external file to inserted into the current file
|===

NOTE: DC indicated that the token is related to the new Derailment Coefficient


See the <<Appendix A>> for a more complete list of tokens/parameters. Note: this list is still incomplete.


==== Example WAG file with INCLUDE

(((ORTS, "Example WAG File")))

Probably some of the BEST examples of how to make use of the {or} ENG/WAG design goals is Erick Cantu with what he has done with the NAVS rolling stock and engines.  Erick heavily makes use of the `INCLUDE` token and new `Freight Anim` options.  I would recommend downloading and looking at one of Erick's SDK files for a good background on his techniques.

An `INCLUDE`  related Excerpt from Elvas Tower Forum is below, where it is pointed out that you can redefine existing sections of a WAG/ENG file with replacement entries that come after the original definitions.

Let's start with the original WVOGrain.wag:

[source]
----
SIMISA@@@@@@@@@@JINX0D0t______

Wagon ( WVOGrain
        comment( WVO Covered hopper, hi-hip version)
        comment( Physics by Chris Lee)
        Type ( Freight )
        WagonShape ( WVOGrain.s )
        Size ( 3.243m 4.728m 17.503m)
        comment( 23.776t empty, 106.747t full )
        Mass ( 73.78t )
        WheelRadius ( 36in/2 )
        InertiaTensor ( Box (3m 3.6m 13.5m) )
        Coupling (
                Type ( Automatic )
                Spring (
                        Stiffness ( 1e6N/m 5e6N/m )
                        Damping ( 1e6N/m 1e6N/m )
                        Break ( 5.1e8N 5.1e8N )
                        r0 ( 20cm 30cm )
                )
                comment( CouplingHasRigidConnection () )
                Velocity ( 0.1m/s )
        )
        Buffers (
                Spring (
                        Stiffness ( 1e6N/m 5e6N/m )
                        Damping ( 1e6N/m/s 1e6N/m/s )
                        r0 ( 0m 1e9 )
                )
                Centre ( 0.5 )
                Radius ( 1 )
                Angle ( 0.5deg )
        )
                        
        Adheasion ( 0.2 0.4 2 0 )
        DerailRailHeight ( 4cm )
        DerailRailForce ( 2.5N/kg*23t )
        DerailBufferForce ( 400kN )
        NumWheels (     8 )
        Friction (
                871N/m/s                0               1mph            3.26N/m/s               1.8
                5.1N/rad/s              1               -1rad/s         0               1
        )
        Lights  (       2
                                
                Light   (
                        comment( Rear red light flashing dim )
                        Type            ( 0 )
                        Conditions      (
                                Headlight ( 2 )
                                Unit ( 3 )
                        )
                        FadeIn  ( 0.5 )
                        FadeOut ( 0.5 )
                        Cycle           ( 0 )
                        States  (       2
                                State   (
                                        Duration ( 0.35 )
                                        LightColour ( 80ff0000 )
                                        Position ( 0.0 1.2 -8.955 )
                                        Azimuth ( -180 -180 -180 )
                                        Transition ( 0 )
                                        Radius ( 1.0 )
                                )
                                State   (
                                        Duration ( 0.35 )
                                        LightColour ( 00000000 )
                                        Position ( 0.0 1.2 -8.955 )
                                        Azimuth ( -180 -180 -180 )
                                        Transition ( 0 )
                                        Radius ( 1.0 )
                                )
                        )
                )
                Light   (
                        comment( Rear red light flashing bright )
                        Type            ( 0 )
                        Conditions      (
                                Headlight ( 3 )
                                Unit ( 3 )
                        )
                        FadeIn  ( 0.5 )
                        FadeOut ( 0.5 )
                        Cycle           ( 0 )
                        States  (       2
                                State   (
                                        Duration ( 0.35 )
                                        LightColour ( 80ff0000 )
                                        Position ( 0.0 1.2 -8.955 )
                                        Azimuth ( -180 -180 -180 )
                                        Transition ( 0 )
                                        Radius ( 1.0 )
                                )
                                State   (
                                        Duration ( 0.35 )
                                        LightColour ( 00000000 )
                                        Position ( 0.0 1.2 -8.955 )
                                        Azimuth ( -180 -180 -180 )
                                        Transition ( 0 )
                                        Radius ( 1.0 )
                                )
                        )
                )
        )

        BrakeEquipmentType( "Handbrake, Triple_valve, Auxilary_reservoir, Emergency_brake_reservoir" )    <----- THIS SECTION HAS SOME SORT OF ISSUE THAT I'M GOING TO CHECK
        BrakeSystemType( "Air_single_pipe" )                                                              <----- IN OPENRAILS AS THE BRAKES AREN'T RECOGNIZED
        MaxBrakeForce( 22.13kN )                                                                            !
                                     
        MaxHandbrakeForce( 22.13kN )                                                                        !
        NumberOfHandbrakeLeverSteps( 100 )
                                                                                                            !
        EmergencyBrakeResMaxPressure( 110 )
        TripleValveRatio( 2.5 )                                                                             !
        MaxReleaseRate( 2.27 )
        MaxApplicationRate( 1.717 )                                                                         !
        MaxAuxilaryChargingRate( 1 )
        EmergencyResCapacity( 2.604 )
        EmergencyResChargingRate( 1 )                                                                       !
        BrakeCylinderPressureForMaxBrakeBrakeForce( 64 )                                                 <-----------------------------------------------------------------------

        Sound ( "GenFreightWag1.sms" )
)
----

Make a new brake system section and typed it in a STD_Wag_Brake.inc:

[source]
----

        BrakeEquipmentType ( "Handbrake, Triple_valve, Auxilary_reservoir, Emergency_brake_reservoir" )
        BrakeSystemType( "Air_single_pipe" )
        MaxBrakeForce( 78kN )
        MaxHandbrakeForce ( 57.2kN )
        NumberOfHandbrakeLeverSteps( 100 )
        EmergencyBrakeResMaxPressure( 110 )
        TripleValveRatio( 2.5 )
        EmergencyResVolumeMultiplier ( 1.461 )
        MaxReleaseRate( 22.2 )
        MaxApplicationRate( 13.9 )
        MaxAuxilaryChargingRate( 20 )
        EmergencyResCapacity( 2.025ft^3 )
        EmergencyResChargingRate( 20 )
        BrakePipeVolume ( 0.307ft^3 )
        BrakeCylinderPressureForMaxBrakeBrakeForce( 90 )
----

Make an `Openrails` folder inside the WVOGrain folder, where I placed a text file with the following text called `WVOGrain.wag` (the well known include method, with comments)

[source]
----
                                                                           <----- REQUIRED EMPTY LINE
include ( "..\\WVOGrain.wag" )                                             <----- CALLS THE ORIGINAL WAG FILE
Wagon (                                                                    <----- THIS MEANS: INSERT THE NEXT LINES IN THE WAGON SECTION
        include ( "..\\..\\Common.inc\\Wagons\\Std_Wag_Brakes.inc" )       <----- CALLS THE .INC FILE WITH THE NEW PARAMETERS
)                                                                          <----- CLOSE THE WAGON SECTION
----

[NOTE]
This trick is in the manual, where it explains how to add instructions to remove the trees on rails in a route without touching the original .trk definition file.

The final result, to {or}, would be:

[source]
----
SIMISA@@@@@@@@@@JINX0D0t______                                                              <---- START OF THE ORIGINAL WVOGRAIN.WAG

Wagon ( WVOGrain
        comment( WVO Covered hopper, hi-hip version)
        comment( Physics by Chris Lee)
        Type ( Freight )
        WagonShape ( WVOGrain.s )
        Size ( 3.243m 4.728m 17.503m)
        comment( 23.776t empty, 106.747t full )
        Mass ( 73.78t )
        WheelRadius ( 36in/2 )
        InertiaTensor ( Box (3m 3.6m 13.5m) )
        Coupling (
                Type ( Automatic )
                Spring (
                        Stiffness ( 1e6N/m 5e6N/m )
                        Damping ( 1e6N/m 1e6N/m )
                        Break ( 5.1e8N 5.1e8N )
                        r0 ( 20cm 30cm )
                )
                comment( CouplingHasRigidConnection () )
                Velocity ( 0.1m/s )
        )
        Buffers (
                Spring (
                        Stiffness ( 1e6N/m 5e6N/m )
                        Damping ( 1e6N/m/s 1e6N/m/s )
                        r0 ( 0m 1e9 )
                )
                Centre ( 0.5 )
                Radius ( 1 )
                Angle ( 0.5deg )
        )
                        
        Adheasion ( 0.2 0.4 2 0 )
        DerailRailHeight ( 4cm )
        DerailRailForce ( 2.5N/kg*23t )
        DerailBufferForce ( 400kN )
        NumWheels (     8 )
        Friction (
                871N/m/s                0               1mph            3.26N/m/s               1.8
                5.1N/rad/s              1               -1rad/s         0               1
        )
        Lights  (       2
                                
                Light   (
                        comment( Rear red light flashing dim )
                        Type            ( 0 )
                        Conditions      (
                                Headlight ( 2 )
                                Unit ( 3 )
                        )
                        FadeIn  ( 0.5 )
                        FadeOut ( 0.5 )
                        Cycle           ( 0 )
                        States  (       2
                                State   (
                                        Duration ( 0.35 )
                                        LightColour ( 80ff0000 )
                                        Position ( 0.0 1.2 -8.955 )
                                        Azimuth ( -180 -180 -180 )
                                        Transition ( 0 )
                                        Radius ( 1.0 )
                                )
                                State   (
                                        Duration ( 0.35 )
                                        LightColour ( 00000000 )
                                        Position ( 0.0 1.2 -8.955 )
                                        Azimuth ( -180 -180 -180 )
                                        Transition ( 0 )
                                        Radius ( 1.0 )
                                )
                        )
                )
                Light   (
                        comment( Rear red light flashing bright )
                        Type            ( 0 )
                        Conditions      (
                                Headlight ( 3 )
                                Unit ( 3 )
                        )
                        FadeIn  ( 0.5 )
                        FadeOut ( 0.5 )
                        Cycle           ( 0 )
                        States  (       2
                                State   (
                                        Duration ( 0.35 )
                                        LightColour ( 80ff0000 )
                                        Position ( 0.0 1.2 -8.955 )
                                        Azimuth ( -180 -180 -180 )
                                        Transition ( 0 )
                                        Radius ( 1.0 )
                                )
                                State   (
                                        Duration ( 0.35 )
                                        LightColour ( 00000000 )
                                        Position ( 0.0 1.2 -8.955 )
                                        Azimuth ( -180 -180 -180 )
                                        Transition ( 0 )
                                        Radius ( 1.0 )
                                )
                        )
                )
        )

        BrakeEquipmentType( "Handbrake, Triple_valve, Auxilary_reservoir, Emergency_brake_reservoir" )
        BrakeSystemType( "Air_single_pipe" )                                                          
        MaxBrakeForce( 22.13kN )                                                                            
                                     
        MaxHandbrakeForce( 22.13kN )                                                                        
        NumberOfHandbrakeLeverSteps( 100 )
                                                                                                            
        EmergencyBrakeResMaxPressure( 110 )
        TripleValveRatio( 2.5 )                                                                             
        MaxReleaseRate( 2.27 )
        MaxApplicationRate( 1.717 )                                                                         
        MaxAuxilaryChargingRate( 1 )
        EmergencyResCapacity( 2.604 )
        EmergencyResChargingRate( 1 )                                                                       
        BrakeCylinderPressureForMaxBrakeBrakeForce( 64 )                                          

        Sound ( "GenFreightWag1.sms" )

        BrakeEquipmentType ( "Handbrake, Triple_valve, Auxilary_reservoir, Emergency_brake_reservoir" )   <---- THIS IS THE ADDED SNIPPET FROM THE .INC
        BrakeSystemType( "Air_single_pipe" )
        MaxBrakeForce( 78kN )
        MaxHandbrakeForce ( 57.2kN )
        NumberOfHandbrakeLeverSteps( 100 )
        EmergencyBrakeResMaxPressure( 110 )
        TripleValveRatio( 2.5 )
        EmergencyResVolumeMultiplier ( 1.461 )
        MaxReleaseRate( 22.2 )
        MaxApplicationRate( 13.9 )
        MaxAuxilaryChargingRate( 20 )
        EmergencyResCapacity( 2.025ft^3 )
        EmergencyResChargingRate( 20 )
        BrakePipeVolume ( 0.307ft^3 )
        BrakeCylinderPressureForMaxBrakeBrakeForce( 90 )                                                 <---- ...TO HERE
)                                                                                              <----- END OF ORIGINAL FILE

----

Clear are mud still, I suppose... more examples are needed.



===== Option 1 - The Benefits of Common Folders for Re-skinners

Lets say you were going to repaint one of Erick's models.  If this is the case, all you really need to do is create a new folder for your content, develop a new SKIN and adjust the existing SHAPE details to refer to the new TEXTURE.  Many of the NAVS releases also include a paint kit release that offer much in the way of guidance for re-skinning, making these the best choice for newcomers that want to give it a try.  

For example, if you used the NAVS 40 ft Boxcar kit as a base model, your WAG files would basically look like this (Taken from CP 40 foot Grain Boxcars by JW Mercer and based on NAVS_BOXCAR_40_PS-TYPE car by Erick Cantu):

----
SIMISA@@@@@@@@@@JINX0D0t______

Wagon ( CP_123541_LD <1>

        Name ( "CPR_Grain_Boxcar_123541_LD" ) <2>

	ORTSFreightAnims (
		MSTSFreightAnimEnabled ( 0 )
		FreightAnimStatic (
			Shape( ../NAVS_COMMON/Boxcar_40_PS-Type/Boxcar_40_PS-Type_carbody_2.s ) <3>
			Offset( 0, 0, 0 )
			FreightWeight( 0lb )
		)
	)

	Include( "../NAVS_COMMON/INCLUDE/AAR_Type-E.inc" ) <4>
	Include( "../NAVS_COMMON/Boxcar_40_PS-Type/PS-Type_40_LD_A3_Conv.inc" )

)
----
<1> The updated name of the new content, Note: Its is common to use ReportingMark_CarNumber_LD or MT (Loaded or Empty) format for naming.
<2> The Updated Descriptive name that will be used.
<3> The updated .S file with the reference to the new texture being applied
<4> The default includes for common data


If you did not have the NAVS 40 Ft Box car installed, you would need to install  `NAVS_Boxcar_40_PS-Type.zip` (Elvas Tower or Trainsim) and `navsfr10.zip` (Trainsim).


===== Option 2 - Completely New Content (with possible help from NAVS)

When creating new content, the amount of work involved can seem daunting at first.  Not only do you need to consider the 3D Model and Texturing details, you need to research the Physics and Sounds for the model.  

For Sounds:: It would be a good recommendation to consider employing the file:  `navsfr10.zip` aka "Open Rails NAVS Car Sounds v2.5" available at trainsim.com.   Current Link: https://www.trainsim.com/forums/downloadnew.php?fid=37487  If you are working on an ENG file, consider `navscf10.zip`, Current Link: https://www.trainsim.com/forums/downloadnew.php?fid=34168

For WAG file:: It would be a good recommendation to use Erick's examples as guidance for how a model {or} WAG or ENG file could be formatted.

[TIP]
If you are not a legacy {MSTS} user, you may not have access to some of the track and weather sounds used by Microsoft's simulator.  If this is the case, you will also want `navs_env.zip` which is a public domain replacement for potentially missing environmental sounds.   

[NOTE]
If you do want to follow the *NAVS* guidelines, consider indicating this in the naming of your content by adding the `NAVS` prefix to your file names.  So what does using this approach mean? Well, it is a well thought out plan for implementing rolling stock that differs greatly from legacy {MSTS}. It is a framework that fully embraces {or} and it's feature set.

Erick Cantu is very particular about how to model a 3D Model freight car.  Using his work as reference material is probably the best place to start.  So let's take a deep dive into a model.

===== Gathering Details

Things that you already know would be Car Dimensions, Coupler Type, Brake Type but you might still need to gather details related to Car Empty Weight and Car Loaded Weight.

So, if we look at a typical NAVS Example again as a guide, what will we find?  Once again we see the minimal MAIN File that references a specific shape .S file and freightAnim references for Reporting Mark decals.  

----
SIMISA@@@@@@@@@@JINX0D0t______

Wagon ( NAVS_Boxcar_NAVX_103100_LD

	ORTSFreightAnims (
		FreightAnimStatic (
			Shape( ../NAVS_COMMON/Boxcar_50_PS-Type/Boxcar_50_PS-Type_carbody_1.s )
			Offset( 0, 0, 0 )
			FreightWeight( 0lb )
		)
		FreightAnimStatic (
			Shape( ../NAVS_COMMON/Boxcar_50_PS-Type/DECALS/A1.s )
			Offset( 0, 0, 0 )
			FreightWeight( 0lb )
		)
	)

	Include( "../NAVS_COMMON/INCLUDE/AAR_Type-E.inc" )
	Include( "../NAVS_COMMON/Boxcar_50_PS-Type/PS-Type_50_LD_A3_Plain.inc" )

)
----

The rest is coming from INCLUDE references... so lets look at those as well.  In the folder reference `../NAVS_COMMON/INCLUDE/AAR_Type-E.inc` we find the Coupler Type details and these values can be shared among many many vehicles.

----
Comment ( //////////AAR Type E Couplers\\\\\\\\\\ )

	Coupling (
		Type ( Automatic )
		Spring (
			Stiffness ( 1.1e6N/m 4.8e6N/m )
			Damping ( 1.1e6N/m/s 1.1e6N/m/s )
			Break ( 390000lbf 390000lbf )
			r0 ( 20cm 30cm )
		)
		Velocity ( 0.1m/s )
	)
	Coupling (
		Type ( Automatic )
		Spring (
			Stiffness ( 1.1e6N/m 4.8e6N/m )
			Damping ( 1.1e6N/m/s 1.1e6N/m/s )
			Break ( 390000lbf 390000lbf )
			r0 ( 20cm 30cm )
		)
		Velocity ( 0.1m/s )
	)
	Buffers (
		Spring (
			Stiffness ( 1e6N/m 5e6N/m )
			Damping ( 1.1e6N/m/s 1.1e6N/m/s )
			r0 ( 0m 1e9 )
		)
		Centre ( 0.5 )
		Radius ( 1 )
		Angle ( 0.5deg )
	)

----

And then we have the references to the specifics of this type of car in `../NAVS_COMMON/Boxcar_50_PS-Type/PS-Type_50_LD_A3_Plain.inc`. This folder would could many alternatives configurations of the main model as well.

----

	WagonShape ( ../NAVS_COMMON/Boxcar_50_PS-Type/Truck_50T_S2_Plain_50_PS-Type.s )

	Type ( Freight )
	Size ( 122.00in 180.00in 652.00in )
	Mass ( 169000lb )
	WheelRadius ( 16.5in )
	NumWheels (	4 )
	AntiSlip ( 0 )

Comment ( //////////Friction\\\\\\\\\\ )

	ORTSBearingType ( Friction )
	ORTSDavis_A ( 225.84lb )
	ORTSDavis_B ( 3.8025lbf/mph )
	ORTSDavis_C ( 0.061998lbf/mph^2 )

Comment ( //////////Brakes - general\\\\\\\\\\ )

	BrakeEquipmentType( "Handbrake, Triple_valve, Auxilary_reservoir, Emergency_brake_reservoir, Retainer_4_Position" )
	BrakeSystemType( "Air_single_pipe" )

	MaxBrakeForce ( 18928lbf )
	Comment ( 169,000-lb loaded weight x 35% loaded cast iron shoe brake ratio x 32% brake shoe friction coefficient )

	MaxHandbrakeForce( 5408lbf )
	Comment ( AAR minimum 10% handbrake ratio x 169,000-lb Gross Rail Load x 32% brake shoe friction coefficient )
	NumberOfHandbrakeLeverSteps( 100 )

	ORTSBrakeShoeFriction 	(
							000.00		0.32
							016.09		0.15
							032.19		0.10
							048.28		0.08
							064.37		0.07
							096.56		0.05
							128.75		0.05
							160.93		0.05
							)

	EmergencyBrakeResMaxPressure( 90 )
	EmergencyResVolumeMultiplier ( 1.50 )
	EmergencyResCapacity( 1.86ft^3 )
	EmergencyResChargingRate( 10 )

	TripleValveRatio( 2.5 )
	MaxReleaseRate( 2.50 )
	MaxApplicationRate( 10.00 )
	MaxAuxilaryChargingRate( 11 )
	BrakeCylinderPressureForMaxBrakeBrakeForce( 70 )
	
  	Sound (	"freight_33_LD_castiron.sms" )

----

Notice how Erick has carefully layed out the design of the overall `WAG` file and the related INCLUDES to allow for sharing of common settings and to allow for a refinement of specific details.  Also note that the CAR BODY is actually a Freight Anim entry and the MAIN BODY of the vehicle is actually based on the type of BOGEY used.  A novel idea that is worth imitating in our own designs.  The TRUCK texture file (shared among all variants) is located in the same folder as  `../NAVS_COMMON/Boxcar_50_PS-Type/PS-Type_50_LD_A3_Plain.inc` while the car body texture and decal texture is located in the same location as the main WAG file.


While you can still use a *default* MSTS-like WAG file with {or}, after seeing what Erick has done, you might be able to see why embracing the new way could be beneficial.  This NAVS method is very re-painter-friendly and the fact that Erick also supplies a layered BITMAP file is the ultimate in "being nice to re-painters".

[TIP]
My recommendation is to use these settings as a guide for making new USA Based Rolling stock.  If you would like guidance on other types of vehicles, I would recommend using the resources at Peter Newell's Coals to Newcastle website: https://www.coalstonewcastle.com.au/physics/

[NOTE]
It's up to you how you want to handle your ENG and WAG files.  You can even go with the location reference of \common\ 



==== Another Example of Rolling Stock 

Here is an example of a traditional MSTS style WAG file for USA style rolling stock.  This is a BLLW release.  It contains NONE of the new tokens related to {or} specifically so should work reliably in MSTS as well.  It does utilize `FreightAnim` though the WAG for this car is to an EMPTY car, so the freight anim setting is commented out.  In {OR}, only one Coupling entry is used, so {OR} will only need to see one in the WAG file.


[NOTE]
The `SIMISA@@@@@@@@@@JINX0D0t______` entry is a header requirement of [msts] and is not required for {or}

----
SIMISA@@@@@@@@@@JINX0D0t______
 
Wagon ( BLLW-H21a-PRR01
    Type ( Freight )
    Comment ( BLLW H21a 2.0 Model by Thomas J Pearce )
    Comment ( Models setup for Empty Coal or Ore Loads )
    Comment ( Freightanim ( BLLW-Coal.s 1 1 ) )
    Comment ( Freightanim ( BLLW-Ore.s 1 1 ) )
    Name ( "BLLW H21a PRR 137788 CK" )
    WagonShape ( BLLW-H21a-PRR01.s )
	Size ( 2.965933m 3.463495m 13.28m )
	CentreOfGravity ( 0m 1.771784m 0m )
    Mass       ( 22.90641t )
    WheelRadius ( 0.4604005m )
	InertiaTensor ( Box (2.965933m 3.463495m 13.28m) )
    Coupling (
		Type ( Automatic )
		Spring (
			Stiffness ( 9.8e5N/m 1.76e6N/m )
			Damping ( 1.77e6N/m/s 1.77e6N/m/s )
			Break ( 2.45e7N 1.78e6N )
			r0 ( 0cm 4cm )
		)
		Comment ( CouplingHasRigidConnection ( 1 ) )
		Velocity ( 0.1m/s )
	)
	Coupling (
		Type ( Automatic )
		Spring (
			Stiffness ( 9.8e5N/m 1.76e6N/m )
			Damping ( 1.77e6N/m/s 1.77e6N/m/s )
			Break ( 2.45e6N 1.78e6N )
			r0 ( 0cm 4cm )
		)
		CouplingHasRigidConnection ( 1 )
		Velocity ( -0.1m/s )
	)
	Buffers (
		Spring (
			Stiffness ( 9.8e5N/m 9.8e5N/m )
			Damping ( 1.7e6N/m/s 1.7e6N/m/s )
			r0 ( 20cm 30cm )
		)
		Centre ( 0.5 )
		Radius ( 1 )
		Angle ( 0.5deg )
	)
    Adheasion ( 0.2 0.4 2 0 )
    DerailRailHeight ( 4cm )
    DerailRailForce ( 2.5*27t )
    DerailBufferForce ( 400kN )
    NumWheels ( 8 )
    Friction (
        100N/m/s        1        -1mph        0        1
        5.1N/rad/s        1        -1rad/s        0        1
    )
    BrakeEquipmentType( "Handbrake, Triple_valve, Auxilary_reservoir, Emergency_brake_reservoir" )
    BrakeSystemType( "Air_single_pipe" )
    MaxBrakeForce( 50kN )
 
    MaxHandbrakeForce( 35kN )
    NumberOfHandbrakeLeverSteps( 100 )
 
    TripleValveRatio( 2.5 )
    MaxReleaseRate( 15 )
    MaxApplicationRate( 25 )
    MaxAuxilaryChargingRate( 5 )
    EmergencyResCapacity( 7 )
    EmergencyResChargingRate( 5 )
    EmergencyBrakeResMaxPressure( 90 )
    BrakeCylinderPressureForMaxBrakeBrakeForce( 50 )
 
      Sound (    "GenFreightWag2.sms" )
)
----

If you keep up with changes in {or}, you will see that some items have changes to be a bit more logical, for instance, if you supply the new DERAIL COEFICIENT tokens then you no longer need to supply `NUMWHEELS` as `ORTSNumAxles` from the Derail values makes it redundant.  Additionally, you only need to supply one `COUPLING` token, not two.   Refer to Derail Coefficient section of the {or} manual for further details.


== Specifying lights on locomotives and wagons


=== Introduction
In Microsoft Train Simulator, you can use the in-built lighting system to create a variety of lights for locomotives and wagons, including headlights, warning lights, and ditch lights. These lights can be used on both computer-controlled and player-driveable trains. The lights can be set to be steady or flashing, and can also be programmed to change based on certain parameters, such as a penalty brake application, or to turn on automatically based on the time of day or weather.

Lights are specified as part of a locomotive/wagon’s .eng file (the same file that defines the physical characteristics of the unit, such as its height and weight, and its cab controls).  Essentially, a set of conditions is defined and then lights that should light in this case are listed).  Like all of the hand-editable files in Train Simulator, the .eng file can be edited in any Unicode text editor.

==== Available Tokens for Lights 

* Type  Glow Cone
* FadeIn 
* FadeOut 
* Cycle 
* Headlight 
* Unit 
* Penalty 
* Control 
* Service 
* TimeOfDay 
* Weather 
* Coupling 
* Duration 
* LightColour 
* Position 
* Radius 
* Azimuth 
* Elevation 
* Transition 
* Angle 

==== Setting requirements 

The first thing you must specify is when you want the light or lights in question to come on.  This is done by setting a number of flags to define the requirements for the lights concerned to light – if no requirements are listed, the light will always be on.

Possible Requirements

* Headlight (0)  (ignore headlight control status)
* Headlight (1) (the headlight control is at “Off”)
* Headlight (2)  (the headlight control is at “Dim”)
* Headlight (3)  (the headlight control is at “Bright”)
* -----
* Unit (0) (ignore unit status)
* Unit (1) (the unit is in the train but isn’t at the front or back)
* Unit (2) (the unit is the frontmost unit of the train)
* Unit (3) (the unit is the rearmost unit of the train)
* -----
* Penalty (0) (ignore penalty status)
* Penalty (1) (the train has not “stopped due to a penalty brake application”)
* Penalty (2) (penalty) (the train has stopped due to a penalty brake application” (useful for specifying an emergency warning light)
* -----
* Control (0) (ignore control status) 
* Control (1) (the player is not control of the unit [i.e. it is a helper locomotive or wagon) 
* Control (2) (the player is in control of the unit)
* -----
* Service (0) (ignore service status)
* Service (1) (the unit is not in service e.g. a failed train lying in a siding)
* Service (2) (the unit is in service)
* -----
* TimeOfDay (0) (ignore time of day)
* TimeOfDay (1) (only come on if it’s daytime)
* TimeOfDay (2) (only come on if it’s night
* -----
* Weather (0) (ignore weather)
* Weather (1) (only come on if it’s fine)
* Weather (2) (only come on if it’s raining)
* Weather (3) (only come on if it’s snowing)
* -----
* Coupling (0) (ignore coupling status)
* Coupling (1) (original front of wagon is coupled)
* Coupling (2) (original rear of wagon is coupled)
* Coupling (3) (both ends of wagon are coupled)



==== Defining lights

Once you have defined a set of requirements, you must list all the lights which you want to light when those requirements are fulfilled.

Type of light:: Two types of lights can be defined in Train Simulator.  

Glow:: Two textured triangles.  Glows are relatively inexpensive in terms of processing time and are perfect for use when you merely wish to show that a light is on rather than off.  They do not affect polygons around them (i.e. they do not “light things up”).

Cone:: A “real” light which has an effect on the polygons around it.  Again, this takes more processing time than a glow and should only be used if you wish to “light something up” as opposed to merely showing a light is on.  Headlights are a suitable use for cone lights – one cone can simulate the light from a bank of headlights, with a glow being used to highlight each individual light if desired.


`Type(n) (where n = 0 is glow, n = 1 is cone)`


==== Fade-in and Fade-out times

These values simply let you define a number of seconds that the light will take to brighten to the brightness of its current state when it is lit, and the number of seconds it will take to die away when it is switched off.  If you specify 0 for both values, the light will light and darken instantaneously.

`FadeIn(t) (where t is the time in seconds)`
`FadeOut(t) (where t is the time in seconds)`


==== Cycle

If this value is set to 1, the light’s states will be cycled through first forwards, then backwards and so on (e.g. 1, 2, 3, 4, 5, 4, 3, 2, 1, 2, 3, 4…).  If this value is left as 0, the states will be played through in order repeatedly (e.g. 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4…)

`Cycle(n) (where n = 0 is play in order repeatedly, n = 1 is cycle)`

==== States

A light has a number of states – a state is simply the form of the light at a given time.  States can be played through in order repeatedly or made to cycle backwards and forwards (see above).  For example, to define a red flashing light, you would define one state that had the light bright red for 1 second and another that had it off for one second.  When the two states were cycled between, the light would appear to flash.  By altering colours, coordinates and durations of states, you can make lights appear to change colour, move around or flash.

A state is made up of the following values:

* Duration(t) Specifies the duration of this light state where t is the time in seconds.

* Colour(aarrggbb) A 32-bit hexadecimal value specifying the colour and translucency of the
light.  aa, rr, gg, bb are 8-bit hexadecimal values specifying the translucency (how "solid" the light is - this only affects glows) and red, green and blue colour components of the light colour respectively.  (If you are not familiar with hexadecimal, a brief explanation is included in the appendices of this document).

* Position(x y z) The position offset in Cartesian coordinates from the centre of the unit.

* Radius(r) This is the radius of the light sphere for cone lights and the radius of
the polygon "disc" for glow lights.

* Azimuth(min centre max) This specifies the heading (rotation about the Y-axis) of glow lights – in the simplest case min, centre and max can all be set to the same angle (in degrees).  For more complex situations where you want to define the arc of the light you can specify for example -45, 0 and 45 degrees respectively to produce a light with a 90 degree arc.  Essentially glow lights attempt to always face the camera but are limited by the azimuth and elevation settings.  The best way to see what the values do is to experiment - set up a light with a set of values and then move the camera around it to see what happens.

* Elevation(min centre max) This specifies the elevation (rotation about the X-axis) of glow lights and (apart from the axis of effect) works identically to the azimuth.

* Transition(n) This specifies how the transition from one state to the next occurs - if n equals zero then the transition is instantaneous, if it is one then the light parameters are interpolated from this state to the next.

* Angle(n) (Cone lights only) the radius of the cone, in degrees.

==== Examples

Here are a few examples, taken from the Dash 9 .eng file.

===== Example 1 – the Dash 9’s front headlights

----
Lights	(	10
		Light	(
			comment( Sphere of light )
			Type		( 1 )
			Conditions	(
				Headlight ( 3 )
				Unit ( 2 )
				)
			Cycle	( 0 )
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( ffffffff )
					Position ( 0.0 3.5 18 )
					Transition ( 0 )
					Radius ( 400.0 )
					Angle ( 15.0 )
					)
				)
			)
		Light	(
			comment( Head light dim )
			Type		( 0 )
			Conditions	(
				Headlight ( 2 )
				Unit ( 2 )
				)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle	( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ffffff )
					Position ( 0.15 3.20 9.679 )
					Azimuth ( 0.0 -5.0 5.0 )
					Transition ( 0 )
					Radius ( 1.0 )
					)
				)
			)
		Light	(
			comment( Head light bright )
			Type		( 0 )
			Conditions	(
				Headlight ( 3 )
				Unit ( 2 )
				)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle	( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( ffffffff )
					Position ( 0.15 3.20 9.679 )
					Azimuth ( 0.0 -5.0 5.0 )
					Transition ( 0 )
					Radius ( 1.0 )
					)
				)
			)
		
Light	(
			comment( Head light bright )
			Type		( 0 )
			Conditions	(
				Headlight ( 3 )
				Unit ( 2 )
				)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( ffffffff )
					Position ( 0.15 3.20 9.679 )
					Azimuth ( 0.0 -5.0 5.0 )
					Transition ( 0 )
					Radius ( 1.0 )
					)
				)
			)

----


===== Example 2 – the Dash 9’s front right flashing (ditch) light.

----
Light	(
			comment( Front right flashing light )
			Type		( 0 )
			Conditions	(
				Headlight ( 3 )
				Unit ( 2 )
				)
			Cycle	( 0 )
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			States	(	2
				State	(
					Duration ( 0.3 )
					LightColour ( ffffffff )
					Position ( -0.60932 1.98713 10.600 )
					Azimuth ( 0 -17.0 -17.0 )
					Transition ( 0 )
					Radius ( 1.5 )
					)
				State	(
					Duration ( 0.3 )
					LightColour ( 00000000 )
					Position ( -0.60932 1.98713 10.600 )
					Azimuth ( 0 -17.0 -17.0 )
					Transition ( 0 )
					Radius ( 1.5 )
					)

				)
			)
----

===== Example 3 – the Dash 9’s rear red light
----
		Light	(
			comment( Rear red light )
			Type		( 0 )
			Conditions	(
				Headlight ( 3 )
				Unit ( 2 )
				)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle	( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( 0.98651 2.12618 -10.677706 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.5 )
					)
				)
			)

		)
----

=== A brief explanation of hexadecimal numbers

Hexadecimal is a base 16 counting system used by computers.  Humans generally use base 10.  In base 10, we have a units column, a tens column, a hundreds (ten squared) column, etc. and numbers can be described by specifying a value for each column.  

For example, 57 has 5 in the tens column and 7 in the units column and (5 * 10) + 7 * 1 = 57.  

In base 16 you have a units column, a sixteens column, a 256s (16 squared) column, etc.  The extra
digits are A to F so you count in hex like this : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A (10 in decimal), B (11 in decimal), C (12), D (13), E (14), F (15), 10 (remember this is hex so that's one in the 16s column and zero in the units column giving you 16).  

Another example the hex number 4D is 4 in the 16s column and D in the units column, but D is 13 so that’s (4 * 16) + (13 * 1) =64 + 13 = 77.

In the case of lights, hexadecimal values are used to set an alpha, red, green and blue value for a light.  Each value is set by a two-digit hexadecimal number, so can be anything between 00 (zero) and FF (F in the 16s column and F in the units column, so since F=15 that’s (15*16) + (15*1) = 240 + 15 = 255).  So a two-digit hexadecimal number can be anything between 0 and 255, i.e. there are 256 possible values.

Therefore the following setting:

`0000FF00`

…would result in a light that has no alpha (i.e. it’s completely “transparent”), no red, full green and no blue.  The result would be a transparent green light.

A more realistic example is:

`80ff0000`

The first two values (80) control the alpha. 80 = 8*16 = 128, so this light will be half-alphaed, or semi-transparent.
The two red values are set to ff (255, as explained above) so the light’s red value is at maximum.  Since the green and blue values are set to 00, the light will be bright red (if they were set to ff as well, the colours would combine together to form a bright white light).

One final example.  The value:

`60808000`

Would result in a yellow, slightly more than half transparent (i.e. more transparent than the red light above) yellow light.


==== Effects

Available tokens for Effects

* StackFX 
* CylindersFX 
* WhistleFX 
* SafetyValvesFX 
* Exhaust 
* Cylinders2FX {or}
* CompressorFX {or}
* GeneratorFX {or}
* Injectors1FX {or}
* Injectors2FX {or}
* HeatingSteamBoilerFX {or}
* WagonGeneratorFX {or}
* WagonSmokeFX {or}
* HeatingHoseFX {or}
* WaterScoopFX {or}
* TenderWaterOverflowFX {or}
* BearingHotboxFX {or}

==== Freight Animations

Available tokens for Freight Animations

* FreightAnim 
* IntakePoint  FuelWater FuelCoal FuelWood FuelSand FuelDiesel FreightGeneral FreightLivestock FreightFuel FreightGrain FreightCoal FreightGrvel FreightSand
* ORTSFreightAnims {or}
* FreightAnimContinuous {or}
* WagonEmptyWeight {or}
* EmptyMaxBrakeForce {or}
* EmptyMaxHandbrakeForce {or}
* EmptyORTSDavis_A {or}
* EmptyORTSDavis_B {or}
* EmptyORTSDavis_C {or}
* EmptyCentreOfGravity_Y {or}
* EmptyORTSWagonFrontalArea {or}
* EmptyORTSDavisDragConstant {or}
* FreightWeightWhenFull {or}
* FullMaxBrakeForce {or}
* FullMaxHandbrakeForce {or}
* FullORTSDavis_A {or}
* FullORTSDavis_B {or}
* FullORTSDavis_C {or}
* FullCentreOfGravity_Y {or}
* FullORTSWagonFrontalArea {or}
* FullORTSDavisDragConstant {or}
* MSTSFreightAnimEnabled {or}
* IsGondola {or}
* UnloadingStartDelay {or}
* FullAtStart {or}
* Shape {or}
* MaxHeight {or}
* MinHeight {or}
* ORTSWaterScoopFillElevation {or}
* ORTSWaterScoopDepth {or}
* ORTSWaterScoopWidth {or}